title = "Lumi"
gitRepoUrl = "https://github.com/astridyz/Lumi"

gitSourceBranch = "main"
changelog = true

classOrder = [
    "Session",
    "State",
    "Enums",
    "CommandBuilder",
    "OptionBuilder",
    "Guild",
    "Role",
    "Channel",
    "Member",
    "Message",
    "User",
    "Application",
    "Command Response"
]

[navbar]
title = ""

[docusaurus]
onBrokenLinks = "throw"
onBrokenMarkdownLinks = "warn"
favicon = "favicon.svg"

[navbar.logo]
alt = "Lumi"
src = "/logo.svg"

[home]
includeReadme = false

[footer]
copyright = "Built using Docusaurus and Moonwave. Released under the <a href=\"https://github.com/astridyz/Lumi/blob/main/LICENSE\" target=\"_blank\">MIT License</a>."   