title = "Lumi"
gitRepoUrl = "https://github.com/astridyz/Lumi"

gitSourceBranch = "main"
changelog = true

classOrder = [
    "Session",
    "Containers"
]

[navbar]
title = ""

[docusaurus]
onBrokenLinks = "throw"
onBrokenMarkdownLinks = "warn"
favicon = "/static/favicon.svg"

[navbar.logo]
alt = "Lumi"
src = "/logo.svg"

[home]
includeReadme = false

[footer]
style = "dark"
copyright = "Copyright © 2024 Astrid. Built with Moonwave and Docusaurus"